name: tiki_kv
description: Key value storage for Tiki.
version: 0.1.1
homepage: https://mytiki.com
repository: https://github.com/tiki/tiki_kv
issue_tracker: https://github.com/tiki/tiki_kv/issues

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite_sqlcipher: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
